project:
  type: book

number-depth: 1

book:
  title: "It is as if you were doing paperwork"
  author: "Pippin Barr & Devolution"
  date: "3/17/2025"
  chapters:
    - index.qmd
    - ./content/info.qmd
    - ./content/commits.qmd
    - ./content/process-journal.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    toc-depth: 1
  docx:
    toc: true
    number-sections: true
    highlight-style: github