project:
  type: book

number-depth: 0

book:
  title: "It is as if you were playing chess"
  author: "Pippin Barr & Devolution"
  date: "3/17/2025"
  chapters:
    - index.qmd
    - ./content/info.qmd
    - ./content/press.qmd
    - ./content/commits.qmd
    - ./content/journal.qmd
    - ./content/blog-posts.qmd
    - ./content/pressabout.qmd

bibliography: ../sharedContent/references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    toc: false
  docx:
    toc: false
    number-sections: true
    highlight-style: github