# readme.md {.unnumbered}

This is the process documentation for the game *It is as if you were playing chess* (2016) by Pippin Barr.

* Read the **Press Kit** (@sec-presskit) for more details on the game and press information
* Read the **Design Journal** (@sec-journal) for high-level reflections on the design and development process
* Read the **Blog Posts** (@sec-blogposts) for public-facing writings while creating the game
* Read the **Commit History** (@sec-commits) for detailed, moment-to-moment insights into the development process
* Look at the **File Structure** (@sec-filestructure) for the evolution of the source code
* Loot at **Press** (@sec-pressabout) to read others writing about the game

## A note on the text

The text has been edited for print, but remains as close to the original as possible. Its main purpose is to provide the original material for exploration, the data is preserved *as is* and not updated.

The original project was already accompanied by a process documentation, but not developed with the help of a repository, only uploaded to one later (2022).

## It is as if you were...

See: *Love*
