project:
  type: book

number-depth: 1

book:
  title: "It is as if you were on your phone"
  author: "Pippin Barr & Devolution"
  date: "3/17/2025"
  chapters:
    - index.qmd
    - ./press_20250303/readme.qmd
    - why.qmd
    - journal.qmd
    - commits.qmd
    - todo_20250110.qmd
    - todo_20250127.qmd
    - todo_20250130.qmd
    - todo_20250221.qmd
    - todo_20250227.qmd
    - todo_20250316.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    