project:
  type: book

number-depth: 0
number-sections: true

book:
  title: "It is as if you were doing work (2017)"
  subtitle: "The evolution of..."
  author: "Pippin Barr & Devolution"
  abstract: "@ A MAZE. / Berlin 2025"

  chapters:
    - index.qmd
    - ./content/press/readme.qmd
    - ./content/journal.qmd
    - ./content/correspondence.qmd
    - ./content/blog-posts.qmd
    - ./content/to-do.qmd
    - ./content/commits.qmd
    - ./content/filestructure.qmd
    - ./content/pressabout/readme.qmd
    - ./content/imprint.qmd

bibliography: ../sharedContent/references.bib
csl: ../sharedContent/chicago-mod.csl

format:
  html:
    theme:
      - cosmo
      - brand
    toc-depth: 2
    link-external-icon: false
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt
    toc: false
  docx:
    toc: false
    highlight-style: github
  epub:
    toc: false