project:
  type: book

number-depth: 0

book:
  title: "It is as if you were growing stuff"
  subtitle: "asdf"
  author: "Pippin Barr x Devolution"
  date: "3/17/2025"
  chapters:
    - index.qmd
    - ./content/commits.qmd
    - ./content/dialogue.qmd
    - ./content/booklets.qmd
    - ./content/onstage.qmd
    - ./content/miroboards.qmd
    - ./content/credits.qmd

bibliography: ../sharedContent/references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    toc: false
  docx:
    toc: false
    number-sections: true
    highlight-style: github