project:
  type: book

number-depth: 0

book:
  title: "It is as if you were growing stuff"
  subtitle: "asdf"
  author: "Pippin Barr x Devolution"
  date: "3/17/2025"
  chapters:
    - index.qmd
    - ./content/commits.qmd
    - ./content/journal.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    toc-depth: 1
  docx:
    toc: true
    number-sections: true
    highlight-style: github