project:
  type: book

number-depth: 0
number-sections: true

book:
  title: "It is as if you were growing stuff"
  author: "Pippin Barr x Devolution"
  abstract: "@ A MAZE. / Berlin 2025"
  chapters:
    - index.qmd
    - content/dialogue.qmd
    - content/booklets.qmd
    - content/onstage.qmd
    - content/program.qmd
    - content/dessauerpress.qmd
    - content/miroboard.qmd
    - content/timelines.qmd
    - content/titles.qmd
    - content/exhibition.qmd
    - content/versions.qmd
    - content/commits.qmd
    - content/filestructure.qmd
    - content/imprint.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    toc-depth: 2
    link-external-icon: false
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt
    toc: false
  docx:
    toc: false
    number-sections: true
    highlight-style: github
  epub:
    toc: false