project:
  type: book

number-depth: 0

book:
  title: "It is as if you were making love (2018)"
  subtitle: "The Process / Documentation / Devolution / Journey of..."
  author: "Pippin Barr x Devolution"
  abstract: "@ A MAZE. / Berlin 2025"
  chapters:
    - index.qmd
    - ./content/press/readme.qmd
    - ./content/manifesto.qmd
    - ./content/commits.qmd
    - ./content/journal.qmd
    - ./content/to-do.qmd
    - ./content/related-work.qmd
    - ./content/pressabout.qmd
    - ./content/filestructure.qmd

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    toc: false
  docx:
    toc: false
    number-sections: true
    highlight-style: github