# booklets.md

## 2025-03-05 Csongor: Too much changes on one day... need to commit!

Let's just start with this first short reminder that we need to start working on the booklets. And by *we* I mean me / us (the Devolution team). All this restructuring has taken some time... and I don't want to make the mistake of not committing my changes. And I will be working on a different computer tomorrow. 

But you can already see some ideas in the folder structure.

## 2025-03-17 Csongor: Quatro

I'm not 100% sure this is the right direction, but I feel we need to come up with a good pipeline for designing & printing the booklets... we've already done a lot of research, which was good, but the structure is a mess. Ultimately we'll need PDFs / InDesign for the layout, but to get the content together we need something that works in a repository (and maybe with markdown files as they are our source material).

I have been testing a few things over the last few days / weeks... lets go with [Quatro](https://quarto.org/). Yes, I could have chosen another one, but this seems to be a good compromise between a lot of things. 

## 2025-03-28 Pippin

Took a look at some of this stuff! This is possibly more your area of expertise than mind. Quatro seems pretty reasonable to me?

## 2025-03-27 Csongor: The Stuff Booklets Are Made Of

This *sinking in* always takes a while... this slowly getting a feel for the material. Reading, researching, understanding. I keep forgetting how much I love it. Yes, these materials are your repositories now.

Looking at the repositories, I almost feel like I can see two ideas taking shape:  
One is the ongoing development and refinement of ideas and routines around MDMA, with each repository exploring, experimenting, improving something.  
The other is the evolution of your own take on Speculative Play.
Or am I forcing my own interpretation on this?

Do you even want to hear this? Should I stop? Feels strange…

A better feeling for the booklets, both in terms of content, but also in terms of structure. This has been bothering me for a while (how much accompanying material? what kind? how to contextualize?), but now I see a path...

I made an [overview](/booklets/readme.md) where you can check out the first rough versions. The page also contains some todos, we are far from finished.

To summarize the ideas:

- a booklet for *Phone* 
- a booklet for *Love* 
- a booklet for *Work* 
    - still thinking about integrating this with excerpts from *The Stuff Games Are Made Of* and maybe also [*Documenting Trajectories in Design Space*](https://dl.acm.org/doi/10.1145/3235765.3235767) 
    - but maybe we don't need that anymore (show, don't tell?) 
- one booklet for *Chess* and *Paperwork* and *Text Adventure*, or should we separate? 
- one booklet as *Designer's Notebook*, maybe with some nice and inspiring quotes 
- one booklet for the *Designer Is Present*, or...?
- aaand one booklet to rule them all...

This last one troubles me. I want to have some kind of overarching thing that summarizes things, but I can't find the form. A *catalog*, a *meta* booklet. The issue feels similar to [on stage](onstage.md). Is it ok to just include this dialogue? Is it enough? Too self-referential? How to contextualize it? A *curator's note*, an *introduction* by someone else...? Who?

So many questions! Didn't I started with that I see the path...!?

## 2025-04-01 Pippin: Metabooklets and drawings

Hey this all makes sense to me! I don't have a sense of the psychic or monetary cost of the numbers of booklets. I kind of love the idea of *too many booklets*? I like the idea of booklets of variable sizes indicating something tangible about the projects and the methodological approach. A booklet of *Text Adventure* would be tiny, and that's kind of intriguing and cool?

The *Meta* booklet is crucial. I guess our dialogue has branched now because this is a dialog and it's in `booklets.md` instead of `dialogue.md`. However that works, I think it'll be a fun one. As I said on the call and maybe somewhere else... I've found this very strange meta-meta-meta conversation excellent and I'm here for your expertise in thinking about an exhibiting/revealing/exploring design process more than anything else. So your voice is, you know, pretty crucial.

Also *drawings*. If I am right in sensing a mild anxiety in you about the rigidly textual nature of my approach to things... I have a lot of random drawings, I do them all the time, and we could throw them in for absolutely no reason other than to break things up. Might be "wrong" in terms of not being from the repositories? Maybe we don't care? Maybe we do? Not sure.

## 2025-04-03 Csongor: ❤️
