project:
  type: book

number-depth: 0
number-sections: true

book:
  title: "It is as if you were on your phone (2025)"
  subtitle: "The evolution of..."
  author: "Pippin Barr x Devolution"
  abstract: "@ A MAZE. / Berlin 2025"
  chapters:
    - index.qmd
    - content/press_20250303/readme.qmd
    - content/why.qmd
    - content/commits.qmd
    - content/journal.qmd
    - content/todos.qmd
    - content/imprint.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    toc-depth: 2
    link-external-icon: false
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt
    toc: false
  docx:
    toc: false
    highlight-style: github
  epub:
    toc: false